### PR TITLE
Adds Wfuzz in web

### PR DESCRIPTION
**Pull request by rohithasrk**

### CODE REVIEW

**Review by CodeMaxx — APPROVED** [review]

**Comment by jaybosamiya** [comment]
Any idea how this compares to [dirbuster](https://www.owasp.org/index.php/Category:OWASP_DirBuster_Project)?

I haven't used Wfuzz before, but have used dirbuster.

Also, paging @DhavalKapil. Have you used Wfuzz?

**Comment by rohithasrk** [comment]
Both seem to be really similar. Maybe reading the description https://github.com/xmendez/wfuzz would help.

**Comment by DhavalKapil** [comment]
Never used `Wfuzz` before. It seems to have more features than DirBuster though.

**Comment by jaybosamiya** [comment]
More features + not Java. I like this tool :) :)

**Review by jaybosamiya — APPROVED** [review]

**Pull request merged**
